### ISSUE TITLE
package.json: Incorrect "main" value causing "Cannot find module 'state-machine'" error

### ISSUE THREAD

**Issue by mmikitka** [davestewart/javascript-state-machine#9]
I've been struggling with integrating this package into a Node app; I've encountered a couple of problems:

1. *Error: Cannot find module 'state-machine'*
I assume that this is caused by an incorrect "main" value in package.json (the file, lib/state-machine.js) is not included in the package. Thinking that the file must be built, I ran *npm build* to no avail.

Possible solution: Change "main" value to "src/StateMachine.js"

2. "SyntaxError: Unexpected token import"
So I changed "main" to "src/StateMachine.js" and I received the following error which I assume is caused by Babel not being loaded.

Possible solution: Unsure

Please advise on how I should proceed.

Aside: It would be really helpful to have installation and configuration instructions on the GitHub page, and to ensure that the instructions function properly in vanilla environments. You may have lots of features and decent documentation, but unless one can integrate the package quickly into multiple popular environments (e.g., Node, Web ), I suspect that most people would look for another package.

**Comment by davestewart** [comment]
Hey,

Thanks for checking out the package.

Sorry you're having integration issues. I have to admit this end of the toolchain is something I'm not the best at.

When I wrote this last year, I didn't have any Node experience; I have a little now, so I might be able to help. Can you point or post to a sample Node setup I could install, and I'll take a look to see how I can get it working? I have some time tomorrow, so I might be able to crack it.

Cheers,
Dave

**Comment by mmikitka** [comment]
@davestewart - thanks for the quick response.

To reproduce the issue, I recommend running the following commands in a vanilla Node 6.x (LTS) and Node 7.x (active) Docker container:

1. docker pull node:6
1. docker run -it node:6 /bin/bash
1. mkdir -p /tmp/node-fsm
1. cd /tmp/node-fsm
1. npm install davestewart/javascript-state-machine
1. cat <<EOF > test.js
> require('state-machine');
> var fsm = new StateMachine({});
> EOF
1. node test.js

(Then repeat with node:7)

Also, to simplify the installation process, is there any way to reduce the number of dependencies? When I run *npm install*, 550 packages are installed. I realize that most of these are > grand-children, but the number can be reduced by ensuring a minimal set of dependencies. Perhaps remove the Babel dependency in favour of ES2015 native?

Thanks for your help.

**Comment by davestewart** [comment]
Thanks for the detailed instructions. 

Just trying to release another project right now, but hopefully I can find time to fit this in.

Cheers,
Dave

**Comment by davestewart** [comment]
Hey, sorry that it seems I've been ignoring this issue; I've been in the process of securing an NPM package name to publish to, which I think will solve the issue.

Hoping to have this resolved by next week, so if you're still looking to use StateMachine, hopefully I'll have good news for you 😄

**Comment by davestewart** [comment]
OK, this is finally fixed! Sorry for the wait...

So I managed to secure the NPM package name `state-machine` and have configured it to publish only the main libs:

- https://www.npmjs.com/package/state-machine

You should now be able to install directly from NPM, with a tiny download, and import StateMachine directly:

- https://github.com/davestewart/javascript-state-machine/blob/master/docs/main/install.md

Let me know if this all works for you, as it's only my second NPM package.

Cheers,
Dave

**Comment by mmikitka** [comment]
@davestewart Thanks for following-up on this. I am still seeing an exception on the 'import' call - perhaps due to the lack of webpack.config.js and a reference to the Bable loader (I notice that the "build" script in package.json invokes webpack)?

Ideally, the steps in my second comment, (re: Docker) work without exception.

Thanks,

**Comment by davestewart** [comment]
Hey,

Yes, it is indeed the build process that is the stumbling block here, I need to take some time to work out how best to build a multi-part library. I think it's this, so I'l need to update webpack:

- https://github.com/webpack/webpack/tree/master/examples/multi-part-library

I might even switch to use Rollup, but I need to find the time to test the damn stuff.

On the plus side, I've got a workflow sorted now where I can test the package install locally with node, so that bit shouldn't trip me up anyway.

**Comment by davestewart** [comment]
So I've got a version working where I pack everything into a single file `main.js` and the code from node would be:

```
var StateMachine = require('state-machine').StateMachine;
var fsm = new StateMachine({});
```

In ES6, the main files are imported as:

```
import { StateMachine, StateHelper } from 'state-machine'
```

In the browser, `StateMachine` and `StateHelper` are loaded as globals.

So I'm pretty sure this works, thought I need to double-check the ES6 import.

I'll try and find time to do this today, and we should be good to go!

Thanks for being so patient 😝

**Comment by mmikitka** [comment]
Thanks, Dave

**Comment by davestewart** [comment]
OK - think it's done now!

Let me know if it works OK for you :)

**Comment by mmikitka** [comment]
@davestewart Works for me, as well.

>$ docker run -it node:6 /bin/bash
root@5b11a1de243f:/# mkdir -p /tmp/node-fsm
root@5b11a1de243f:/# cd /tmp/node-fsm
root@5b11a1de243f:/tmp/node-fsm# npm install state-machine
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.10.3
npm info attempt registry request try #1 at 12:44:16 PM
npm http request GET https://registry.npmjs.org/state-machine
npm http 200 https://registry.npmjs.org/state-machine
npm info addNameTag [ 'state-machine', 'latest' ]
npm info retry fetch attempt 1 at 12:44:16 PM
npm info attempt registry request try #1 at 12:44:16 PM
npm http fetch GET https://registry.npmjs.org/state-machine/-/state-machine-1.0.1.tgz
npm http fetch 200 https://registry.npmjs.org/state-machine/-/state-machine-1.0.1.tgz
npm info lifecycle state-machine@1.0.1~preinstall: state-machine@1.0.1
npm info linkStuff state-machine@1.0.1
npm info lifecycle state-machine@1.0.1~install: state-machine@1.0.1
npm info lifecycle state-machine@1.0.1~postinstall: state-machine@1.0.1
/tmp/node-fsm
`-- state-machine@1.0.1 

> npm WARN enoent ENOENT: no such file or directory, open '/tmp/node-fsm/package.json'
npm WARN node-fsm No description
npm WARN node-fsm No repository field.
npm WARN node-fsm No README data
npm WARN node-fsm No license field.
npm info ok 

> root@5b11a1de243f:/tmp/node-fsm# cat <<EOF > test.js
> var StateMachine = require("state-machine").StateMachine;
> var fsm = new StateMachine({transitions:['next: a > b > c']});
> fsm.go('b');
> fsm.go('c');
> fsm.go('a');
> console.log(fsm.state);
> EOF

> root@5b11a1de243f:/tmp/node-fsm# node test.js 
No transition exists from "c" to "a"
c

**Comment by davestewart** [comment]
Awesome!

Well, if you're still in the market for using it, I hope you like it.

I'll be here for any questions.

Cheers,
Dave
